### ISSUE TITLE
请问节内小结如何处理？

### ISSUE THREAD

**Issue by hanxiaomax** [zhimengfan1990/seuthesix#1]
请问如果我需要添加1.2.2这样的小节应该如何操作呢？使用`\subsection`并不会添加序号

**Comment by hanxiaomax** [comment]
序号可以显示但是不是黑体

**Comment by zhimengfan1990** [comment]
模板设计subsection标题格式为宋体。可以改，但是我不建议更改。
而且我个人也觉得subsection 标题用宋体更好看。
:)

**Comment by hanxiaomax** [comment]
感谢回复~
可以用\renewcommand覆盖一下吗?能否指点一下如何写？

**Comment by zhimengfan1990** [comment]
前导部分加上

\ctexset{
subsection/format=\raggedright, 
subsection/nameformat={\normalsize\bfseries}, 
subsection/numberformat={\normalsize\bfseries},
subsection/titleformat={\normalsize\bfseries},
}

**Comment by zhimengfan1990** [comment]
\ctexset{
subsection/format=\raggedright, 
subsection/nameformat={\normalsize\bfseries}, subsection/numberformat={\normalsize\bfseries},
subsection/titleformat={\normalsize\bfseries},
}

**Comment by zhimengfan1990** [comment]
\ctexset{
subsection/format=\raggedright, 
subsection/nameformat={\normalsize\bfseries}, subsection/numberformat={\normalsize\bfseries},
subsection/titleformat={\normalsize\bfseries},
}

**Comment by hanxiaomax** [comment]
谢谢
