### ISSUE TITLE
术语与符号约定

### ISSUE THREAD

**Issue by jhfanseu** [zhimengfan1990/seuthesix#3]
使用\nomenclature命令为什么无效呢，增加了额外的术语约定，编译后不显示，仍然显示的是例子中那两个，请问是什么原因呢？谢谢！

**Comment by zhimengfan1990** [comment]
术语要用makeindex 编译。具体方法参考makefile_masters.bat等脚本。

**Comment by zhimengfan1990** [comment]
脚本可以一站式的完成所有编译任务。

**Comment by jhfanseu** [comment]
原来如此，多谢！
