### ISSUE TITLE
术语与符号约定

### ISSUE THREAD

**Issue by jhfanseu** [zhimengfan1990/seuthesix#4]
术语与符号约定右栏无法左对齐，这个可以更改吗？
![qq 20160315103328](https://cloud.githubusercontent.com/assets/14249813/13763288/408dedb0-ea99-11e5-9538-1e628a08125e.png)

**Comment by zhimengfan1990** [comment]
不太清楚，nomenclature这个宏包不是我写的。你可以看看它的文档，有没有这个feature。命令行输入

texdoc nomenclo 

再回车,就能看到。

**Comment by jhfanseu** [comment]
更改了.cls文件里的默认配置\printnomenclature，把距离变大就可以对齐

**Comment by zhimengfan1990** [comment]
谢谢，已经更新了，距离设置为1in。
